import traceback
from pyrogram import filters
from core.bot import app
from utils.helpers import get_reply_target
from modules.social.actions import action

COMMANDS = [
    "hug", "kiss", "bite", "slap", "kick", "cuddle", "pat", "highfive",
    "flirt", "love", "crush", "couple", "propose", "marriage", "divorce"
]

@app.on_message(filters.command(COMMANDS))
async def social(_, message):
    command = (message.command or [""])[0].lower().lstrip("/")

    if command == "couple":
        return await message.reply("💞 Use /couple in a group to get a random couple.")

    if not message.from_user:
        return await message.reply("❌ I couldn't identify the user who sent this command.")

    target = get_reply_target(message)
    if not target:
        return await message.reply("❌ Reply to a user's message to use this command.")

    if target.is_bot:
        return await message.reply("🤖 You can't target a bot with this command.")
    if target.id == message.from_user.id:
        return await message.reply("❌ You can't use this command on yourself.")

    try:
        text = await action(message, command, target)
        # Captions are plain text with Telegram mention HTML generated by action().
        await message.reply(text, parse_mode="html", disable_web_page_preview=True)
    except Exception:
        traceback.print_exc()
        await message.reply("❌ I couldn't process that social command right now. Please try again.")
